### ISSUE TITLE
Contributing is a little confusing

### ISSUE THREAD

**Issue by stickeegreg** [open-telemetry/opentelemetry-php#1096]
**Is your feature request related to a problem?**
Not a problem but I wanted to contribute to the `open-telemetry/exporter-otlp` composer packagage. Looking it up on Packagist shows the GitHub repo as https://github.com/opentelemetry-php/exporter-otlp but this says "[READONLY]" in the description and has no issues tab.

**Describe the solution you'd like**
It would be nice if the `README.md` for that repository said something along the lines of "To contribute, see the https://github.com/open-telemetry/opentelemetry-php repository".

**Comment by brettmc** [comment]
Agreed, and I've been thinking about that recently. The problem is that it's a mirror of a directory (which we need to do so that packagist works, it can't deal with subdirectories, at least that's my understanding).

I tried to add some badges to make it clearer what's upstream and mirror - I'm fine with adding a little sentence like you've described to the various README files...

**Comment by stickeegreg** [comment]
Cool, I'm happy to make a PR if you'd like

**Comment by brettmc** [comment]
> Cool, I'm happy to make a PR if you'd like

Yes, please!

**Comment by stickeegreg** [comment]
Created #1108 as a first go at this
