### ISSUE TITLE
OpenTelemetry guessing intention incorrectly

### ISSUE THREAD

**Issue by dgafka** [open-telemetry/opentelemetry-php#1138]
**Describe your environment** - `php 8.2`

**Context**

I am not sure how it works under the hood, yet OpenTelemetry is trying to guess if given scope is closed correctly from my understanding. 

## 1. Notice when result of $span->activate() is assigned to variable, yet not used

Having such code:
```php
$span = $tracer->spanBuilder('test');
$context = $span->activate();
```
If we don't close the $context within current PHP function scope it will throw an notice:

```bash
Notice: Scope: missing call to Scope::detach() for scope #352, created 
	at OpenTelemetry.Context.Context.activate(Context.php:84)
	at OpenTelemetry.API.Trace.Span.activate(Span.php:51)
```

The scenario for this is where we don't want to close the context within the current PHP function scope is for separate Before and After method, where we will close the current scope by accessing scope and context in following way:

```php
$currentContext = Context::storage()->scope();
$currentRelatedSpan = Span::getCurrent();
$currentContext->detach();
$currentRelatedSpan->end();
```

## 2. Exception when result of $span->activate() is not assigned to variable

Having such code:
```php
$span = $tracer->spanBuilder('test');
$span->activate();
```
If we don't assign activate span, exception will be thrown.

```bash
Scope: unexpected call to Scope::detach() for scope #785, scope successfully detached but another scope should have been detached first

/data/app/vendor/open-telemetry/context/DebugScope.php:43
```

The scenario for this is the same as above. OpenTelemetry tries to guess something which works correctly, yet using singleton instances, to get and close the scopes correctly.

**Comment by brettmc** [comment]
In (1) yes that's correct, as part of a destructor we check for whether any scopes have been left open. The warning is telling you that there is a bug - all activated scopes need to be detached. You open it, you close it.

Think of detaching scope as "deactivating" an active span. What it means is that the next span created will not be a child of that span, but whatever was the previously active span, or a new "root" span if nothing is currently active.

If you have multiple activated spans, you must detach their scopes in LIFO order ie, activate span A, activate span B, detach scope B, detach scope A. Normally you'd also end span A and B at the same time that you're detaching the associated scope, but that's not necessary - a span can run for longer than it was active for, and it could also be active for longer than it was running for.

It doesn't matter how you get a reference to the scope for an activated span (`$scope = $span->activate()` or `$span->activate(); $scope = Context::storage()->scope`), it's the same scope (and it's not really singleton, either, you can look at how context storage is implemented but think of it more like a stack).

So it looks to me as though in the second example you've activated two spans, but tried to end them out of order.

**Comment by brettmc** [comment]
@dgafka I think I understand a little better now. This is related to `DebugScope` - when you activate a span via `$span->activate()` you get a `DebugScope`, which wraps the "real" scope. This is done to help developers to ensure that activated spans are "deactivated", and if they are not then DebugScope will tell you (at shutdown) and will also tell you where the span was created.

So, when I said earlier that it doesn't matter how you get a reference to the scope, it actually does (sorry!). So, in your second example, you lose the DebugScope by not keeping a reference (which actually means that even if you did deactivate it via some other method, it would still complain).

That said, the "scope detach" issue you mention is real for you; it still doesn't matter how you got a reference to the active scope(s) to detach them, it still looks to me that you've detached them out of order.

Also note that this isn't true of auto-instrumentation via the extension - because post hooks are guaranteed to execute (even on die/exit) then we can be very confident that they are deactivating spans in the correct order. So, the way that they activate spans is a little different: `Context::storage()->attach($span->storeInContext(Context::getCurrent()));`
Doing it that way avoids DebugScope - but it also means you're less likely to know about bugs, which I think are most likely to show up as weird traces (spans incorrectly parented, etc).

**Comment by brettmc** [comment]
As of context v1.0.1 debug scopes can be disabled entirely, see https://github.com/open-telemetry/opentelemetry-php/pull/1205 for details. With this feature enabled, you won't see the notices.
