### ISSUE TITLE
Implement a ValueObserver Instrument for the Metrics API

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#121]
We would like to Implement a ValueObserver Instrument for the Metrics API. The spec for the ValueObserver API is defined at the following URL:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#valueobserver

**Comment by ohamuy** [comment]
Hi, I could definitely take this up!

@alolita

**Comment by ohamuy** [comment]
Hey,

@bobstrecansky I was wondering there can i find the specs for the ValueObserver? The provided link does not include the specifications for it! Am I missing something?

**Comment by prondubuisi** [comment]
Hello @ohamuy the specs for the Metrics API should be available [here ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md), It appears that `ValueObserver`, as well as other observers, have been removed from the specs. 

I think these changes took place with this [commit](https://github.com/open-telemetry/opentelemetry-specification/tree/12b5b27d4b6a4c0197560f508f0be3c38d190dc4/specification/metrics)

@bobstrecansky It looks like we would avoid creating issues for the Metrics API since it is still experimental?

**Comment by bobstrecansky** [comment]
Yeah this looks to be a very vestigial issue!  I think we can close it.  @ohamuy - happy to help you find another issue; you should be able to pick anything in the [Tracing Project](https://github.com/open-telemetry/opentelemetry-php/projects/1)
