### ISSUE TITLE
[contrib-auto-yii]Getting unknown property: yii\web\ErrorAction::actionMethod

### ISSUE THREAD

**Issue by buildyuan** [open-telemetry/opentelemetry-php#1228]
```
https://github.com/opentelemetry-php/example-auto-yii
Can you run that and then compare to your setup? If it works, then we'd love a documentation patch that clarifies the setup please :)
```

_Originally posted by @brettmc in https://github.com/open-telemetry/opentelemetry-php/issues/1196#issuecomment-1865487920_

### what happens
I tried this demo [opentelemetry-php/example-auto-yii](https://github.com/opentelemetry-php/example-auto-yii) 

it not work you visit some  actions Method/Action, such as 
```php
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'id' => [
                'class' => 'app\controllers\user\IdAction',
            ]
        ];
    }
```
this actions  extend `\yii\base\Action`, do not extend `yii\base\InlineAction` , they do not have `$actionMethod`( the controller method that this inline action is associated with).
the web throw exception like this: 
```
Unknown Property – [yii\base\UnknownPropertyException](https://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Getting unknown property: yii\web\ErrorAction::actionMethod
```
### Describe the solution you'd like
I annotated `vendor/open-telemetry/opentelemetry-auto-yii/src/YiiInstrumentation.php` line 137.
use `$_SERVER['REQUEST_URI']`  to fill 'http.route'

//$route = YiiInstrumentation::normalizeRouteName(get_class($controller), $action->actionMethod);
$route = $_SERVER['REQUEST_URI'];

### What do you think

It works good.

I am confused why it is necessary to obtain the route in such a complex way. Is there any information I missed?

```php
    protected static function normalizeRouteName(string $controllerClassName, string $controllerMethod): string
    {
        $lastSegment = strrchr($controllerClassName, '\\');
        
        if ($lastSegment === false) {
            return $controllerClassName . '.' . $controllerMethod;
        }

        return substr($lastSegment, 1) . '.' . $controllerMethod;
    }
```

**Comment by brettmc** [comment]
Thanks @buildyuan I understand the issue now. We can't use request URI as the http.route, because the spec says it must be low-cardinality: https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name
If it's not possible to use a low-cardinality route name, then the recommendation is to just use the http method.
So, the correct solution may be to check whether $action extends `InlineAction`, and if it does not, then have the post hook do nothing (unless you know of another way to find an appropriate low-cardinality route).

> I am confused why it is necessary to obtain the route in such a complex way. Is there any information I missed?

Sorry I don't know, I didn't write the original code. But, if you can come up with a better way, then PRs are always welcome :)

**Comment by buildyuan** [comment]
> We can't use request URI as the http.route, because the spec says it must be low-cardinality: https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name

That's that I need.

I just read this document , if there is a request such as
 `/logicSvrWebAPI/ad/v1/describeInstances?orgId=0&page=1&pageSize=10&keyword=&RequestId=9a5bcf0cfbto-99e4`,
could you tell me what the appropriate outcome `http.route` would be?

1. logicSvrWebAPI.describeInstances
2. describeInstances
3. others?  please tell me

**Comment by brettmc** [comment]
> I just read this document , if there is a request such as
/logicSvrWebAPI/ad/v1/describeInstances?orgId=0&page=1&pageSize=10&keyword=&RequestId=9a5bcf0cfbto-99e4,
could you tell me what the appropriate outcome http.route would be?

I think that both `logicSrvWebAPI.describeInstances` and `describeInstances` are good low-cardinality route names. Usually, if a web framework allows users to name routes (or provide a path with placeholders, eg `/users/:id/orders`) then we would use that.
If not, then we can use something like `ControllerName::actionName`.
Otherwise, then the spec says it should just be `{http.method}`

**Comment by brettmc** [comment]
@buildyuan a new version of the package has just been released which should resolve your issue. Please test it out :)
