### ISSUE TITLE
[PHP 8.4] Fixes for implicit nullability deprecation

### ISSUE THREAD

**Issue by andypost** [open-telemetry/opentelemetry-php#1296]
**Is your feature request related to a problem?**

[RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
[PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

**Describe the solution you'd like**
Testing of Drupal 11 showed this deprecations

**Describe alternatives you've considered**
Fix deprecated

**Additional context**
probably more deprecations coming for PHP 8.4

**Comment by ivanmunozruiz** [comment]
hello! this merge doesn't have any @stable version?

**Comment by brettmc** [comment]
@ivanmunozruiz I believe all of the changes from the related PR have been tagged for some time. Is there something I've missed?

**Comment by ivanmunozruiz** [comment]
What I mean is, this change doesnt have any tag? I have installed the last one 0.0.17 but doesn't contain this change

**Comment by brettmc** [comment]
OK I think I understand now. We haven't published this whole repo to packagist for about 2 years, and yes 0.0.17 was the latest stable back then. We now git-split opentelemetry into a bunch of sub-repos which are individually published on [packagist](https://packagist.org/packages/open-telemetry/) (open-telemetry/api, open-telemetry/sdk, etc)

I'm not sure how you were installing 0.0.17 since AFAIK it's not available on packagist, but it's ancient and not what you want.
