### ISSUE TITLE
OpenTelemetry Specification 1.34.0 Release - Common - OpenTelemetry clients MUST follow SemVer 2.0.0.

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#1331]
OpenTelemetry clients MUST follow SemVer 2.0.0. 

We need to follow the following specification change:
OpenTelemetry clients MUST follow SemVer 2.0.0. 
https://github.com/open-telemetry/opentelemetry-specification/pull/4039

**Comment by brettmc** [comment]
Checked and confirmed that we do follow SemVer 2.0.0 (we might consider using for example `beta.1` instead of `beta1`, although the latter still seems ok per semver spec).
Also, since we only have one package each for `API`, `SDK` etc, we don't need to worry about versioning them together as the spec suggests.

I think we can close this.
