### ISSUE TITLE
Question about scope detaching 

### ISSUE THREAD

**Issue by davidpocar** [open-telemetry/opentelemetry-php#1379]
Hello, sorry if this is not a place for asking questions but I did not find a place for questions. 

_Context_ 
I am instrumenting some libraries in our repo and I am looking at otel contrib packages for inspiration. 

_Question_ 
What I don't quite get is why would one sometimes detach a scope first, then ask if the current context changed (?) _(example [GuzzleInstrumentation](https://github.com/opentelemetry-php/contrib-auto-guzzle/blob/main/src/GuzzleInstrumentation.php#L91))_. Because other packages only do the detaching part and do not check for the current context changes _(example [HttpClientInstrumentation](https://github.com/opentelemetry-php/contrib-auto-symfony/blob/main/src/HttpClientInstrumentation.php#L124))_?

**Comment by brettmc** [comment]
I don't have a solid answer (and I had the same confusion when the [very first auto-instrumentation library](https://github.com/open-telemetry/opentelemetry-php-contrib/pull/78/files#diff-678a7fef7e9bf623833798442e1ecfa76fd521a8ff9d424c9060172942a8ad03R78) was submitted with the current-context checking.
My understanding at the time was that it was guarding against somebody manually ending a span outside of auto-instrumentation (since auto-instrumentation post hooks blindly close whatever happens to be the active span). I'm not aware of any actual field reports of this happening, so it seems authors are taking or leaving that extra check with no known consequences.

**Comment by davidpocar** [comment]
Thanks!
