### ISSUE TITLE
Add Infection for Mutation testing as part of CI/CD

### ISSUE THREAD

**Issue by prondubuisi** [open-telemetry/opentelemetry-php#203]
Following discussions with  @dkarlovi and @bobstrecansky we are considering add mutation testing as part of our CI/CD

For more information on infection, you can check here https://infection.github.io/guide/

I am already working on this

**Comment by dkarlovi** [comment]
A short primer on mutation tests: your tests will cover a certain feature, your code coverage will claim a certain part of the code was "covered".

Mutation testing uses this information against you and does the following:
1. checks the coverage of a certain line
2. intentionally breaks that line in some way (which makes sense)
3. runs the tests which claim to cover it
4. if the tests now fail, it's considered OK, if the tests pas, it's considered not OK (so, opposite from the usual flow)

Example, let's say we have this code:

```php
function increment(int $step): void
{
    $this->counter += $step;
}
```

If you mutate the code like this:
```diff
function increment(int $step): void
{
-    $this->counter += $step;
+    $this->counter += 1;
}
```

and rerun the tests, they by definition **must** fail since the code is now different, and they claim to "cover" it. If they don't, they don't cover it fully, they only cover a subset (one path or something, in this case `$step = 1`).

The obvious solution is adding more tests, which is exactly what you want anyway. Basically, mutation testing is verifying your code coverage result and telling you if it's lying or not.

**Comment by prondubuisi** [comment]
Thanks for sharing @dkarlovi  I did read a blog post while trying to understand what was happening under the hood https://medium.com/@maks_rafalko/infection-mutation-testing-framework-c9ccf02eefd1

**Comment by bobstrecansky** [comment]
We've closed this for now as it hasn't taken highest priority.  Feel free to reopen if you'd like to work on this!
