### ISSUE TITLE
User Research Feedback Improvements - Creating a Symfony Bundle

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#220]
We'd like to create a Symfony bundle in order to make it easier to adopt OpenTelemetry PHP in Symfony projects.  This feedback came from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d4Y)

**Comment by bobstrecansky** [comment]
@prondubuisi is going to work on this.

**Comment by prondubuisi** [comment]
Hello @dkarlovi , I am getting started with this task later in the day, are there any goals that we have for this? Also, I think the official[ Symfony docs](https://symfony.com/doc/current/bundles.html) are exhaustive on building bundles, but if you have additional resources that can help us reach the goal for the bundle that would be nice.

**Comment by prondubuisi** [comment]
Okay @dkarlovi , noted with thanks.

**Comment by bobstrecansky** [comment]
@prondubuisi - are you still planning on finishing this up?

**Comment by prondubuisi** [comment]
Hello @bobstrecansky , I intend to continue work on all the tasks I am tagged on.  Thanks

**Comment by prondubuisi** [comment]
Hello @tidal, please feel free to take this up. Thanks.

**Comment by Blacksmoke16** [comment]
@tidal I'd also be quite interested in helping out!

**Comment by tidal** [comment]
@prondubuisi 
Ok, great, I will.

In general, where do you guys want the symfony bundle to live? If it's intended to be part of the open-telemetry organization, it needs a separate repository (or sub split, etc.) I could run PRs against. Sadly packagist can only cope with packages in a root directory.

@Blacksmoke16  Sounds good. I have seen you have done a lot of work on this library, so your knowledge is probabably better than mine. Once above question is solved, and I have made some adjustments, I will have some code to push/show in the next days, and we could discuss how to go from there.

**Comment by bobstrecansky** [comment]
@Blacksmoke16 is correct; `opentelemetry-php-contrib` would be the place for the instrumentation!  Thanks for you ideals on this @tidal; looking forward to helping out any way you need!

**Comment by bobstrecansky** [comment]
Yes; that is the pattern that the other language SIGs (including the Collector) are following now.

**Comment by tidal** [comment]
@Blacksmoke16 The problem is not even that Private Packagist is a paid service, but that it's meant to host proprietary packages. So users would have to add [additional configuration](https://getcomposer.org/doc/articles/handling-private-packages.md#usage) to even be able to load the packages.
However all packages/components of [Symfony](https://github.com/symfony/symfony) live in a mono repo as well, but they use subsplits to mirror individual packages to single repos. The [console component](https://github.com/symfony/console) for example.

I wll try for now to make the Symfony bundle work, when I integrate it under `open-telemetry-php` with the root composer.josn. Usually Symfony bundles expect `"type": "symfony-bundle"` in composer.json, since Symfony comes with its own sort of "auto instrumentation" by so called "recipes" (They inject default variables in a .env file etc.). But I guess there is a way to work around this, with a [composer post install script](https://getcomposer.org/doc/articles/scripts.md). I will give it a try.

**Comment by Blacksmoke16** [comment]
@tidal Ahh fair enough, I missed the extra config part.

However, IMO, I wouldn't handicap the bundle just to integrate it into `open-telemetry-php`. It would be best to have a bundle that takes full advantage of Symfony's features, and figure out a distribution solution later. Not much we can really do to work around it it seems. At this point it's just a question of if they'd rather have a dedicated org to house the mirrored repos, or would be okay putting them in this org.

**Comment by tidal** [comment]
Ok, I just tested a minimal symfony bundle living in `opentelemetry-php-contrib`: 
https://github.com/tidal/opentelemetry-php-contrib/blob/sf-bundle-test/instrumentation/symfony/src/OpenTelemetryBundle.php

Adding the open-telemetry/opentelemetry-php-contrib package to a symfony project does result in the bundle to be detected and auto registered (config/bundles.php):
`
return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    OpenTelemetry\Instrumentation\Symfony\OpenTelemetryBundle\OpenTelemetryBundle::class => ['all' => true],
];
`
The second line has been automatically added and is all which is needed to work as a bundle, since the "bundle class" follows symfony's naming convention for bundles.
So there is no problem in shipping the bundle as part of the overall `opentelemetry-php-contrib` package.

I will then proceed to add my code to `opentelemetry-php-contrib` and hopefully by sunday there is something more for you guys to see than an empty bundle.

**Comment by prondubuisi** [comment]
> Yes; that is the pattern that the other language SIGs (including the Collector) are following now.

Hello @bobstrecansky, I think this is the exact opposite. Every Package should be separate and self-containing I think. Communities like that of Symfony thrive in being just minimalist and using only what you need. So having a Symfony package that also has Laravel configs and configs for other frameworks would not really fly. cc @dkarlovi

**Comment by prondubuisi** [comment]
> @tidal Ahh fair enough, I missed the extra config part.
> 
> However, IMO, I wouldn't handicap the bundle just to integrate it into `open-telemetry-php`. It would be best to have a bundle that takes full advantage of Symfony's features, and figure out a distribution solution later. Not much we can really do to work around it it seems. At this point it's just a question of if they'd rather have a dedicated org to house the mirrored repos, or would be okay putting them in this org.

Yeah, I agree. We should get working packages first and figure out how to publish them from https://github.com/open-telemetry/opentelemetry-php-contrib later.

**Comment by tidal** [comment]
Guys, please take a look at the configuration draft for the the symfony bundle. This draft yet only reflects possible configurations to wire up the tracing SDK via dependency injection. It does not yet take into account what is actually recorded and how. This ca be dealt with once the bundle can "tame" all the boilerplate code.
Most entries will have default values and there is (will be) validation for the complete configuration schmema. So when env variables for the service name and exporter dsn are provided, the configuration is actually not required. It's only purpose is to provided a more granular instrumentation when needed:
https://github.com/tidal/otel-apiplatform-example/blob/config-draft/api/config/packages/open_telemetry.yaml

I have addeds ome comments in the yaml file, but if you think I missed something, got something completely wrong, or forgot something, which could possibly be configured (even if the SDK will only provide it in the future), please let me know. 
Btw, this is only an example in yaml. Configuration in Symfony can also be provided in XML or plain PHP. And there can be individual config files per environment (dev, test, staging, prod), which can override values from the global configuration.

In case you are wondering about the application. It's a [API Platform](https://api-platform.com/) project. API Platform is a REST framework plus Frontend and Admin component, which sits on top of Symfony and comes with a lot of neat features. It will make developing and testing a lot of things much easier (including K8S integration, since it ships with Helm charts)

**Comment by Blacksmoke16** [comment]
@tidal I think it's a good start!.

Unfortunately, the SDK doesn't really have a way to configure itself at the moment, so it's not immediately clear _what_ all needs to be configurable, or how that would be setup. Ideally once that is more ironed out the Symfony config could just forward the same config to it, then provide the configured types as services. Until then I think keeping things simple to start will making updating it to use this easier in the future. I.e. focus on the core stuff you have now and can iterate on more advanced/specialized things later on.

Just a few comments/suggestions. 

1. Does it also allow custom services to be used? E.g. `root_sampler: MyApp\Samplers\MySpecialSampler`
1. Yes, it would make sense to allow multiple processors, there's also a `MultiSpanProcessor` that allows wrapping multiple into one type
1. There should probably be some configuration for `ResourceInfo`, which should include the service name by default, along with the application version (prob is a way to get this programmatically?)

**Comment by tidal** [comment]
@Blacksmoke16  Thanks for your feedback!

> Does it also allow custom services to be used? E.g. root_sampler: MyApp\Samplers\MySpecialSampler

Not yet, but I can take care of that. There is always the possibility to create and configure custom services and reference them with @my_service in SF configs.

> Yes, it would make sense to allow multiple processors, there's also a MultiSpanProcessor that allows wrapping multiple into one type

Ok.

> There should probably be some configuration for ResourceInfo, which should include the service name by default, along with the application version (prob is a way to get this programmatically?)

This should be no problem.

> Unfortunately, the SDK doesn't really have a way to configure itself at the moment, 

Symfony [Config ](https://symfony.com/doc/current/components/config.htm) and [Dependency Injection](https://symfony.com/doc/current/components/dependency_injection.html) are standalone components, so it would be possible to reuse/extract this part for the SDK in the future. I will keep this in mind. Futhermore the DI component is [PSR11](https://www.php-fig.org/psr/psr-11/) compatible, so it would be possible to configure DI of other frameworks/packages as well.

Anyway, I will clean up my experimental code and integrate it in my `opentelemetry-php-contrib ` clone so we can have a working example, an we can take it from there.

**Comment by tidal** [comment]
Regarding extracting individual packages from the `opentelemetry-php-contrib` mono-repo:

This is the subtree splitter used by symfony: https://github.com/splitsh/lite
This is a subtree split as a service: https://www.subtreesplit.com/ . I have never used it, but it's free and the service is provided by the author of the DsnParser and used in the SDK and the nyholm/psr7 http client.

**Comment by bobstrecansky** [comment]
Sorry for the additional work!  It's very much appreciated!  Running CI and reviewing.

**Comment by tidal** [comment]
@bobstrecansky 
Don't worry, I have been working on Symfony projects since its version 1, so I new upfront what work this will include.

**Comment by tidal** [comment]
@bobstrecansky  
I believe this task can be closed now. If have created some follow up tasks over at [open-telemetry/opentelemetry-php-contrib/issues](https://github.com/open-telemetry/opentelemetry-php-contrib/issues/) (and probably create some more), in case someone is interested in helping out with improvement or further development.
