### ISSUE TITLE
 User Research Feedback Improvements - Documentation around shouldSample() variables.

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#221]
The shouldSample() call  takes lots of params which are unclear what they do or why I need to pass them explicitly.

This feedback came from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d4Y)

**Comment by bobstrecansky** [comment]
@dkarlovi - we have this documented in the function [here](https://github.com/open-telemetry/opentelemetry-php/blob/92be0025ea8c85097a3cf0789eb244d34bdab787/sdk/Trace/Sampler.php#L16-L30)

Was there another place you were expecting to have this documented?  Maybe in the examples?

**Comment by dkarlovi** [comment]
@bobstrecansky this would definitely be documented as part of user-facing documenation, as discussed in #222. The idea is to explain what this is and why do you need to set it, having different use cases as examples is definitely a plus.

The issue I still see is repeating information visible from the type information.

```php
    /**
     * Returns SamplingResult.
     *
     * @return SamplingResult
     */
    public function shouldSample(

    ): SamplingResult;
```

This is exactly the same information provided three separate times. It creates an illusion of wealth of information since the doc block is "beefy", but when you actually read it for new information, it provided little. I see that other information is similar, rewording the existing information again.

_(NHF anyone who wrote this docblock, it's not meant as a judgement on anyone's good intentions or skill, documentation is **hard**)_

**Comment by brettmc** [comment]
Sampling has been refactored recently (in head, not yet in a released version), which moves the responsibility for sampling decisions into the tracer. Since a user doesn't need to interact with the sampler anymore, this issue might be no longer required? (In fact, in the simple/default case, you don't even need to provide a sampler any more, and you'll get parent-based always-on sampling).
