### ISSUE TITLE
User Research Feedback Improvements - PSR18

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#223]
We'd like to use PSR18 to provide a standard set of interfaces for HTTP clients.

This ticket came from [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d4Q)

**Comment by bobstrecansky** [comment]
I was talking to a coworker about PSR-18 today, and he mentioned that Guzzle7 implements the PSR-18 interfaces natively https://github.com/guzzle/guzzle/blob/master/src/Client.php#L17

This should make our work a lot easier.

**Comment by prondubuisi** [comment]
Thanks for sharing @bobstrecansky I have read this up many times, I just can't wrap my head on what the implementation will look like.

**Comment by dkarlovi** [comment]
See example here: https://gist.github.com/dkarlovi/ec38d1c4cc47b85609c6e2bffa2451e5

The requirement is to inject three things instead of one (which is the cost of abstracting, and one design mistake in the PSR spec could have made it two).

The usage can be seen here: https://github.com/dkarlovi/opentelemetry-php-user-test

My proposal would be this:
1. make a package-specific HTTP client wrapper class which just gets injected with these abstract interfaces, can have some sort of `Client::create()` factory which creates the best client it can
2. make that wrapper the `$client` param for exporters, call `Client::create()` if null
3. this allows auto-wiring and injecting it with Symfony and the bundle in the future, but it also has the same convenience as currently

This means the package doesn't require the current Guzzle packages, it requires:

```
psr/http-client-implementation
psr/http-factory-implementation
```

(it can suggest Guzzle)

And this allows for a fully replaceable HTTP stack within the library.

**Comment by dkarlovi** [comment]
Rough idea of the "wrapper" which gets injected into all exporters, the 

```php
class SpanTransporter
{
    public function __construct(ClientInterface $client, RequestFactoryInterface $requestFactory, StreamFactoryInterface $streamFactory) {}
    
    public static function create(): self
    {
        // try to figure out how to best auto-construct self
    }
    
    public function transport(string $endpointUrl, iterable $spans): int
    {
        try {
            $body = $this->streamFactory->createStream(json_encode($spans));
            $request = $this->requestFactory
                ->createRequest('POST', $endpointUrl)
                ->withBody($body)
                ->withHeader('content-type', 'application/json');
            
            $response = $this->client->sendRequest($request);
        } catch (RequestExceptionInterface $e) {
            return Trace\Exporter::FAILED_NOT_RETRYABLE;
        } catch (NetworkExceptionInterface | ClientExceptionInterface $e) {
            return Trace\Exporter::FAILED_RETRYABLE;
        }

        if ($response->getStatusCode() >= 400 && $response->getStatusCode() < 500) {
            return Trace\Exporter::FAILED_NOT_RETRYABLE;
        }

        if ($response->getStatusCode() >= 500 && $response->getStatusCode() < 600) {
            return Trace\Exporter::FAILED_RETRYABLE;
        }

        return Trace\Exporter::SUCCESS;
    }
}
```

**Comment by bobstrecansky** [comment]
@prondubuisi - are you still planning on working through this?
