### ISSUE TITLE
  User Research Feedback Improvements - Use SetSpanStatus to change the span to an error manually, when catching the exception. 

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#227]
We'd like to be able to use SetSpanStatus to change the span to an error manually while catching an exception.

This ticket is the result of [this comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d5k)

**Comment by prondubuisi** [comment]
Hello @bobstrecansky  @dkarlovi, Does the recordException event solve this problem? I think wrapping  a code block in a try/catch i.e

```
try{
//something
}(Exception $exception){
     $span.recordException($exception);
}
```

Would automatically add the error event to the span

**Comment by bobstrecansky** [comment]
You would need to have some sort of functionality that causes an exception for it to be thrown.  Something akin to:

https://www.w3schools.com/php/php_exception.asp

**Comment by prondubuisi** [comment]
Thanks for the response @bobstrecansky, I am a little confused. Maybe I am missing what the problem here is, as well as the proposed solution. From @dkarlovi  comment, he says " Unclear how, the span code is not equal to the exception code, there's no way to auto-transform the exception (which is an object of type \Throwable) into proper span information." He also continues "Even though I've set the status from the exception, the span doesn't reflect any sort of exception."

**Comment by prondubuisi** [comment]
Maybe a flow description of what is happening and what is expected to happen will help me understand this issue better.

**Comment by bobstrecansky** [comment]
I'll defer to @dkarlovi as he was the one who was proposing the solution.

**Comment by prondubuisi** [comment]
Hello @bobstrecansky I looked at this [comment](https://docs.google.com/document/d/1n43oTVsnydmbpzvhN-5dgPAvRWKZCiugmmR_wg_8ziQ/edit?disco=AAAAHTU6d5k) again, and the commit for the [exception test](https://github.com/dkarlovi/opentelemetry-php-user-test/commit/cda54e62eba88eae95d354b3dfa10105d69b95e4) , notice the similarity with https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/AlwaysOnJaegerExample.php#L59, I think the only issue now is confirming we see the exception properties with Jaeger and Zipkin,  which I don't. Once we can confirm that, I think this should be solved.

**Comment by dkarlovi** [comment]
Correct, if you're able to use `recordException` and get the desired span attributes, consider it solved.

**Comment by bobstrecansky** [comment]
@prondubuisi - did you ever dig into confirming the visibility of the exception properties with Jaeger and Zipkin?

**Comment by bobstrecansky** [comment]
@prondubuisi - just following up here.

**Comment by Blacksmoke16** [comment]
It would probably make sense to change that method to `recordThrowable` and set the span to failed if it's in instance of `Error`. Otherwise, just because an exception is recorded doesn't mean it would cause the span to error.  E.g. if you gracefully handled it. However an `Error` usually would mean you need to fix something in your code.

**Comment by Blacksmoke16** [comment]
@bobstrecansky I think github took my link to a specific comment to mean it would close the whole issue. Should probably reopen this.
