### ISSUE TITLE
Update Zipkin Exporter to conform to latest spec changes

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#295]
Our current implementation of the Zipkin Exporter needs an update to conform to the latest spec. See [Zipkin exporter spec](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk_exporters/zipkin.md#opentelemetry-to-zipkin-transformation).

Work items:
* A lot of mappings have changed for attributes and tags.
* add support for both v1 and v2

**Comment by Grunet** [comment]
Here's what I noticed from a quick skim of [Java's implementation](https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java)

- "op.status_code" is instead "otel.status_code"
- "op.status_description" isn't present
- Has mentions of "otel.dropped_attributes_count" and "otel.dropped_events_count"
    - The former is included here - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L113
    - The lastter is included here - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L144
- Puts a "kind" on the span - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L100
- "parentId" is omitted enitrely if the parent span context isn't valid - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L106
- Has a little more logic around status code and error - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L121

**Comment by Grunet** [comment]
>     * We do have a `SpanKind` implementation here: https://github.com/open-telemetry/opentelemetry-php/blob/f4124e08595bd911d1324e0eaee0593d7c9dc2d0/src/API/Trace/SpanKind.php - Is that different than what you were looking for?

Ah perfect! That at first glance looks like what the other languages have

>     * We also do have tags in the `SpanConverter`: https://github.com/open-telemetry/opentelemetry-php/blob/f4124e08595bd911d1324e0eaee0593d7c9dc2d0/src/Contrib/Zipkin/SpanConverter.php - are the functions in that file different than you were expecting for the tag implementation?  Those haven't been touched in a while, so it may just be that they were updated in the spec and we didn't update accordingly.

I think the commonality between JS and Java's "tags" handling that PHP didn't have was the little bit of extra handling/logic around the status code and error. The other pieces around "tags" handling seemed to line up afaict

**Comment by Grunet** [comment]
So I re-read the spec and a few things cropped up other than the things already mentioned above

- Java/Python don't seem to support the "Remote Endpoint" section of the spec (and JS has a TODO) whereas it seems like other languages might
- The spec mentions in 2 places handling converting from Zipkin format back into OTLP format, but I can't find any evidence of any language having implemented this
- Java/Python haven't implemented handling for a span's event's attributes yet, but other languages might've (e.g. Go)

Here are my raw notes:

Service Name

- Others have different/more handling but I'm not reading anything the PHP implementation is doing against the spec since it allows for the service name to be passed as a constructor parameter 
    - Java - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L162
    - Python - https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/encoder/__init__.py#L280

Span Kind

- Need to make a map that is identity other than KIND_INTERNAL, which gets set to "null"
   - Like in Java - https://github.com/open-telemetry/opentelemetry-java/blob/6ef3091cfb83946372da0d47d70acdf468c9e6c3/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/ZipkinSpanExporter.java#L174

InstrumentationLibrary

- Need to read the "name" and "version" properties off of the SpanDataInterface instance (https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Trace/SpanDataInterface.php#L37) then set them like is done in Java/Python (see above)

Remote endpoint

- OTLP -> Zipkin
    - It doesn't seem like Java or Python support this
    - Per this codesearch (https://grep.app/search?q=remoteEndpoint&filter[repo.pattern][0]=open-telemetry), it seems like .NET, Go, Swift, Ruby, and/or Rust might (with JS having a TODO for it)

- (Where is Zipkin -> OTLP done? I'm not seeing that anywhere in otel-php)

Attribute

- What does this line mean?: "Some attributes defined in semantic convention document maps to the strongly-typed fields of Zipkin spans."

- OTEL-PHP seems to be following Java's approach here in terms of formatting, so I assume it's probably meeting the spec, though I can't say for sure just yet

Status

- This is what the additional handling JS/Java/Python have is for I think. It seems like matching up with them should meet this

Events

- It doesn't look like Java or Python have implemented this part yet, but it seems like others may have
    - Here's where it looks like Go's logic for this lives - https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/zipkin/model.go#L141

Unit of Time

- otel-php seems to be doing the time unit conversions correctly from what I can tell

Request Payload

- The only spots I can see where something should be omitted in the payload if it's empty are "parentId" (also mentioned above) and maybe "tags"
    - Everything else feels like it's either required or will be getting skipped when its empty

Considerations for Legacy (v1) Format

- This seems to have to do with converting from a Zipkin v1 span back into OTLP for,at, but like I mentioned above I'm not seeing any existing mentions of that in the otel-php codebase
    - And maybe I'm just not codesearching for the right things, but I'm not finding any evidence of "Zipkin to Otlp" logic elsewhere in open-telemetry

**Comment by Grunet** [comment]
I think I'll go ahead and get started on the easier, better understand things that need changing for PHP, and in parallel try to sort out what to do about these new concerns (the need for an inverse converter being the main one I think)
