### ISSUE TITLE
failed to run 'composer require open-telemetry/opentelemetry' in Integrating Opentelemetry PHP into Laravel Applications

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-php#350]
I have succeeded run the step 1 in this guide. But every time I run the command in step 2, I will always fail to run it. I am new to php, and I have no idea to solve this problem.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/27889201/121190279-78f9f580-c89d-11eb-8364-ba570eafe0a5.png">

**Comment by prondubuisi** [comment]
Hello @tydhot , the integration guide for Laravel and Symfony needs to be updated to reflect changes with `OpenTelemetry-PHP v.0.0.2`. for version ` v.0.02` we allow the package users to specify their preferred HTTP requirements, rather than doing that by ourselves like in version `v.0.0.1`

For a temporary fix try requiring 

`composer require guzzlehttp/psr7:2.0.0-rc1`

before your require 

` composer require open-telemetry/opentelemetry
`

Another Potential problem would be with the exporters as the parameter requirements have changed also,
You will need to add the following to the imported classes, 

```
use Psr\Http\Client\ClientInterface;
use GuzzleHttp\Psr7\HttpFactory;
```

And lastly, add the following arguments to both  Zipkin and Jaeger exporter constructors 

```
$jaegerExporter = new JaegerExporter(
    'Hello World Web Server Jaeger',
    'http://localhost:9412/api/v2/spans',
    new  ClientInterface(), 
    new HttpFactory(), 
    new HttpFactory()
);

$zipkinExporter = new ZipkinExporter(
    'Hello World Web Server Zipkin',
    'http://localhost:9411/api/v2/spans',
     new  ClientInterface(), 
    new HttpFactory(), 
    new HttpFactory()
);
```
Every other thing should work well.  

I would try updating both guides to reflect these changes by the Weekend. Thanks.

**Comment by tydhot** [comment]
@prondubuisi Thanks! I will try it now :)

**Comment by tydhot** [comment]
hi @prondubuisi , I have success to require otel dependency in the project, I copy the code like below.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/27889201/121287870-fc0a6280-c914-11eb-8cb3-4fc773eec9ae.png">
But after I start server, it would be a error like this:
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/27889201/121287927-17756d80-c915-11eb-92d6-411a001190c2.png">
Maybe I should construct a Context first?
And I copy the exporter constructors like you say, but it would be a error in my ide.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/27889201/121288052-51df0a80-c915-11eb-87c9-eafa689036bf.png">

**Comment by prondubuisi** [comment]
Hello @tydhot , looks like we have further changes introduced by `v.0.0.2`. I think it would be better  for me to create  a sample application locally, then update the docs. 

I will tag you here once that is done by the weekend. Thanks.

**Comment by tydhot** [comment]
@prondubuisi thanks !

**Comment by prondubuisi** [comment]
Hello @tydhot, I have made updates as promised, can you help review this? https://github.com/open-telemetry/opentelemetry-php/pull/361

**Comment by tydhot** [comment]
@prondubuisi Great, thanks a lot! I'll try it later.
