### ISSUE TITLE
Documentation for opentelemetry.io

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#405]
We'd like to add some documentation to the opentelemetry.io website.

the [website_docs](https://github.com/open-telemetry/opentelemetry-php/tree/main/website_docs) folder pushes all of its contents to https://opentelemetry.io/docs/php/

We should include our documentation in there in order to make it easier for end users to adopt our library.

**Comment by chalin** [comment]
The docs might move: for details, see #423. /cc @austinlparker

**Comment by bobstrecansky** [comment]
Yes!  I think we could use a lot more documentation.  That documentation is built here:
https://github.com/open-telemetry/opentelemetry-php/blob/main/website_docs/getting-started.md
Our documentation is unorganized and not complete.  Using other languages as a template would probably help a lot.

**Comment by chalin** [comment]
> Yes! I think we could use a lot more documentation. 

Great. It would help enormously if the PHP docs were in the website repo. Note that other SIGs have made the choice to move their docs to the website repo since we [last exchanged on the topic in September](https://github.com/open-telemetry/opentelemetry-php/issues/423#issuecomment-929217971), including:

- **Java**: https://github.com/open-telemetry/opentelemetry.io/issues/989
- **Python**: https://github.com/open-telemetry/opentelemetry.io/issues/1109 -- still in progress

@cartermp has been driving much of the documentation improvement efforts across languages, and it is much easier for him to do so when the docs are in the website repo before he starts reworking and enhancing the docs. Might you be willing to reconsider your decision for #423 

/cc @austinlparker

**Comment by bobstrecansky** [comment]
@yuktea mentioned she would like to work on this.

**Comment by chalin** [comment]
Thanks @yuktea! Maybe the best would be to coordinate with @cartermp, who has a better idea of what work needs to be done, unless you (@bobstrecansky et all) have specific pages you'd like @yuktea to start working on? 

@yuktea - by the way, the website/communications team meets every other week. For details, see our [Meeting doc](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY). Our next meeting is on March 10.

**Comment by yuktea** [comment]
> Thanks @yuktea! Maybe the best would be to coordinate with @cartermp, who has a better idea of what work needs to be done, unless you (@bobstrecansky et all) have specific pages you'd like @yuktea to start working on?
> 
> @yuktea - by the way, the website/communications team meets every other week. For details, see our [Meeting doc](https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY). Our next meeting is on March 10.

Yes, I'll coordinate with them 👍

**Comment by tidal** [comment]
Closing this issue in favor of https://github.com/open-telemetry/opentelemetry-php/issues/758 , since the website docs are not maintained in this repo anymore.
