### ISSUE TITLE
Revamp examples

### ISSUE THREAD

**Issue by Blacksmoke16** [open-telemetry/opentelemetry-php#426]
As a result of #422, examples will need to be updated to work with the new API. A lot of them are also very similar. IMO it would be better to have the examples show off specific features, like a simple one, child spans, etc. Instead of every type of exporter getting its own example.

_Originally posted by @Blacksmoke16 in https://github.com/open-telemetry/opentelemetry-php/pull/422#discussion_r718126890_

**Comment by tidal** [comment]
In addition it would be good to use snake case for the file names of the examples, as camel case is usually only used for classes, interfaces and traits.

**Comment by brettmc** [comment]
It seems to me that most of the original examples are really developer-focussed integration/regression tests - any thoughts on moving them out of `examples` and into `regression` or something like that? (happy to do this, and get them working again, if they're still useful and required).

**Comment by Blacksmoke16** [comment]
There's also an `Integration` namespaces in `tests/SDK` that could be a good place for some of these types of examples.

I still think the examples would be better served showing how to use higher level concepts of the library (e.g. simple versus parent/child) instead needing one for every tiny feature of the lib. Possibly this would also be a good place for textual docs that can just talk about those features versus needing an entirely new example file that's 95% the same, just with a diff exporter/extra config/data on the spans.

**Comment by tidal** [comment]
@Blacksmoke16 
I agree. The exporter setup is kind of straightforward, especially when one has basic understanding of distributed tracing. Other parts of the SDK/API/Spec are not as intuitive to understand. So for the SF bundle I had to dig through a lot of code
and spec docs to make things work. There is nothing wrong with reading the spec (while it's not always an easy read for non native English speakers), but in the best case someone who builds an instrumentation on top of the SDK, can rely on the SDK documentation itself.
The problem is probably 99% of developers (including me) prefer writing code over writing docs, while most prefer to read good doumentation over digging through code. And keeping docs up to date in a pre alpha state can be kind of a tedious.

**Comment by lalex** [comment]
Could we rework or totally remove examples named `AlwaysOn...` as they show bad pattern of exposing `Sampler`s implementation? Client's code should not rely on sampling decisions made by samplers.

I've noticed it while browsing the source of the Symfony bundle: https://github.com/tidal/otel-sdk-bundle-example-sf5/blob/6b84645171d7f4fac06c82ec857291fb58ffecad/src/EventSubscriber/OtelKernelSubscriber.php#L193

**Comment by tidal** [comment]
> Could we rework or totally remove examples named `AlwaysOn...` as they show bad pattern of exposing `Sampler`s implementation? Client's code should not rely on sampling decisions made by samplers.
> 
> I've noticed it while browsing the source of the Symfony bundle: https://github.com/tidal/otel-sdk-bundle-example-sf5/blob/6b84645171d7f4fac06c82ec857291fb58ffecad/src/EventSubscriber/OtelKernelSubscriber.php#L193

That's not the source code of the Symfony Bundle. However I'm excited somebody found my easter egg, since I actually forgot about it, 
I agree, that the sampling decisions should not be in the examples. They are more confusing, than helpful anyway. 
One simple example for each sampler should be enough.

The sampling decisions are also used in the Symfony/Laravel tutorials, but what I'm more concerned of there is that the shown way of "integrating" via global scope is rather dangerous imo.

**Comment by tidal** [comment]
@stale
你要这样做吗？

**Comment by Grunet** [comment]
Is there anything concrete left to do on this issue? I noticed just now looking at them altogether they're a tad disorganized (I guess at least at the file level) and as a result it's a little hard to tell what's there or not.

Would renaming the files per @tidal's suggestion and then organizing them into folders/sub-folders be enough? Or do folks think more is needed around this area before the beta release?

**Comment by tidal** [comment]
@Grunet 
> Would renaming the files per @tidal's suggestion and then organizing them into folders/sub-folders be enough? Or do folks think more is needed around this area before the beta release?

That would definitly be a great start (there's probably always room for improvement).
However some examples might be outdated or broken.
Especially we should get rid of all:
```php
if (SamplingResult::RECORD_AND_SAMPLE === $samplingResult->getDecision()) {
[...]
```
and try-catch blocks
```php
try {
    $span1 = $tracer->spanBuilder('foo')->startSpan();
    $span1Scope = $span1->activate();

    try {
        $span2 = $tracer->spanBuilder('bar')->startSpan();
        echo 'OpenTelemetry welcomes PHP' . PHP_EOL;
        $span2->end();
    } finally {
        $span1Scope->detach();
        $span1->end();
    }
} catch (Throwable $t) {
    $rootSpan->recordException($t);
} finally {
    //ensure span ends and scope is detached
    $rootScope->detach();
    $rootSpan->end();
}
```

**Comment by MurzNN** [comment]
> which I am exporting to elastic APM to check that it presents as expected

@brettmc Could you please share also the exporter configuration for APM? I've configured "otlp/http" and it doesn't work with Elastic APM collector, but works well with Grafana Tempo collector. And I still can't find any examples of how to make it work, so an example would be very useful!

**Comment by MurzNN** [comment]
@brettmc Did you got any good news about this?

**Comment by brettmc** [comment]
I haven't started yet, and won't for at least a few weeks sorry.
