### ISSUE TITLE
Do not include dropped attribute/links/event counts if there are none

### ISSUE THREAD

**Issue by Blacksmoke16** [open-telemetry/opentelemetry-php#427]
We're including these properties all the time, but the spec says they shouldn't be set if they're `0`.

> This key-value pair should only be recorded when it contains a non-zero value.

Ref: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/sdk_exporters/non-otlp.md#dropped-attributes-count

_Originally posted by @Blacksmoke16 in https://github.com/open-telemetry/opentelemetry-php/pull/422#discussion_r718126627_

**Comment by Grunet** [comment]
I'm a little confused after an initial investigation into this one and feel I may be missing something simple, as it seems like the Span class (from the generated proto/ files) being initialized and returned by both of the "as_otlp_span" methods in the repo that add "dropped_***" attributes will always set its "dropped_***_count" fields to uint32's (or at least I'm not seeing a way to "unset" them and keep them out of any further communication)

- [This](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/OtlpGrpc/SpanConverter.php) and [this](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/OtlpHttp/SpanConverter.php) files where the "dropped_***" keys are currently being added
- Where the Span class [initializes the dropped_attributes_count to 0](https://github.com/open-telemetry/opentelemetry-php/blob/main/proto/Opentelemetry/Proto/Trace/V1/Span.php#L124)
- Where [the setter for the field lives](https://github.com/open-telemetry/opentelemetry-php/blob/main/proto/Opentelemetry/Proto/Trace/V1/Span.php#L579)

**Comment by Grunet** [comment]
FWIW I think I'm realizing after looking at this for Jaeger Thrift spans that the linked spec may actually apply to all of the exporters (unless their specs have language overriding it) and that each exporter may need to do something slightly differently to handle it.

And I think the OTLP to Collector case I looked at above still has the problem with the proto file too afaict.

**Comment by Grunet** [comment]
Oh also it [doesn't look like any language anywhere respects the otel.dropped_links_count afaict](https://grep.app/search?q=otel.dropped_links_count), so maybe that's just "dead spec"

**Comment by Grunet** [comment]
Actually wait I'm not seeing anywhere outside of the Java language library and maybe collector code referencing the keys for dropped attributes and dropped events 

[Lack of otel.dropped_attributes_count](https://grep.app/search?q=otel.dropped_attributes_count)
[Lack of otel.dropped_events_count](https://grep.app/search?q=otel.dropped_events_count)

**Comment by Grunet** [comment]
I opened up [an issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2268) around this in the specification repo

**Comment by Grunet** [comment]
Per the conversation in the associated spec issue, this is implemented in several other languages, I just didn't find them in my original code search.

I can take a look to see if I understand what the PHP changes would be like

**Comment by Grunet** [comment]
So for exporting to Jaeger and Zipkin, I'm guessing it's probably just a matter of updating the span converters to conditionally convert the properties to the corresponding Jaeger and Zipkin constructs (like [how Python did](https://github.com/open-telemetry/opentelemetry-python/search?q=otel.dropped_attributes_count)). It looks like both should be mapped to the respective "Tag" construct for Jaeger and Zipkin (also mentioned in the [Jaeger spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/sdk_exporters/jaeger.md#summary) and the [Zipkin spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/trace/sdk_exporters/jaeger.md#summary))

No gRPC/protobuf to deal with for either since exporting to Jaeger via gRPC wasn't implemented yet (or at least not since I last checked a while ago).

I'm also not noticing any non-OTLP gRPC usage among the exporters listed [here](https://github.com/open-telemetry/opentelemetry-php/tree/main/src/Contrib) in the repo (and this requirement is only for non-OTLP exporters)

But from that link above there are 2 NewRelic specific exporters that might need dealing with. I'm not entirely sure where they'd be expecting this info when it's sent to them. The ZipkinToNewRelic one seems to be expecting Zipkin formatted spans, so maybe could add this to a "tags" key, like is alluded to in [this NewRelic doc](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api/). And the plain NewRelic one seems to be expecting NewRelic-specifically formatted spans, so maybe this should just be added to the "attributes" list, or at least no other spot stands out to me from [this NewRelic doc on the topic](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api#the-span-object-in-the-spans-array)

**Comment by sanketmehta28** [comment]
Hi @bobstrecansky @brettmc @tidal Can you please assign this to me?
