### ISSUE TITLE
TracerProvider factory

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#462]
Per spec (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#opentelemetry-environment-variable-specification): "SDKs `MAY` choose to allow configuration via the environment variables in this specification". It looks like all but one env var required to allow configuring all aspects of a trace provider have been defined. I proposed the addition of `OTEL_TRACES_SPAN_PROCESSORS` in https://github.com/open-telemetry/opentelemetry-specification/issues/2110, but the spec also allows for language-specific env vars, eg `OTEL_PHP_SPAN_PROCESSORS`.

**Is your feature request related to a problem?**
No, this is a convenience feature

**Describe the solution you'd like**
If the environment is configured correctly, I'd like to do something like:
```php
$traceProvider = TraceProviderFactory::createFromEnvironment();
$tracer = $traceProvider->getTracer('foo');
```
Most of the exporters already check for environment variables, but I do see some dependencies on a concrete ClientInterface etc - https://github.com/open-telemetry/opentelemetry-php/issues/448 may fix this.
I also see that SpanConverter is required for exporters, however it also looks like there is a 1:1 relationship between a span exporter and its converter.
There is a placeholder in `ResourceInfo` to auto-create resource info from OTEL_RESOURCE_ATTRIBUTES which could be implemented here too.

**Describe alternatives you've considered**
None.

**Additional context**
Our code all runs in containers (docker or k8s), and where possible we configure things through environment variables rather than through code.
I'm interested in working on this, but seeking feedback first.

**Comment by tidal** [comment]
> Our code all runs in containers (docker or k8s), and where possible we configure things through environment variables rather than through code.

That's good. However I have worked with dozens of companies over the years, and I found out, people do the strangest things, which may not be best pratices. Or in other words, different companies may have different requirements. I also found out "You ain't gonna need it" is a principle which is not really compatible with creating libaries for companies, as there may be a need that configuration has to come from the company toaster delivered by a carrier pigeon (I'm exaggerating a bit, but not much). And the size of a company is not an indicator, whether such requirements exist.

To give a more on practical examples, configuration may come from environment variables via K8S secrets, config maps, etc, or from .env files or from "classic" config files (YAML, JSON, PHP, INI files, etc.) or from a mixture of all approaches, where the concrete mix is also depending on a environment (dev, staging, prod, etc.) and values may overwrite each other. 

A method `TraceProviderFactory::createFromEnvironment()` looks like it is expecting all configuration to be "real" environment variables, while that might not be always possible (for whatever reason). That's at least something worth keeping in mind.

A method `TraceProviderFactory::createFromEnvironment()` also looks like there could be more factory methods in the future like  `fromCheeseCake`, etc. , so the factory would even have more resonsibilities than it already must have. 

One could create a dedicated factory like this `TraceProviderEnvironmentFactory::createt()` which may derive from an abstract factory. However this factory still would have to do a lot of things, validating values, probably normalizing, checking for defaults and creating the TracerProvider, which has a dependency on other objects, which have a dependency on other objects and/or values. So it would include a bit more departments than just fabricating an or several objects.

So, It might be better to extract the configuration part of the factory, which could look like this:
```php
$traceProvider = (new TraceProviderFactory(new EnvironmentConfig()))->create();

````
So we could also have something like this:
```php
$traceProvider = (new TraceProviderFactory(new YamlConfig('config.yaml')))->create();

````
But what to do with those guys who want to mix and match?
Maybe something like this?

```php
$config = new Config;
$config->addProvider(new  EnvironmentProvider());
$config->addProvider(new  EnvFileProvider('.env'));
$config->addProvider(new  YamlProvider('config.yaml'));
$config->addProvider(new  CheeseCakeProvider('config.yummie'));

$traceProvider = (new TraceProviderFactory($config))->create();

````

But wait, there is more. 
The [spec says](https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e249f60c3a5f68746f5e84d10195ba41a79/specification/trace/sdk.md#span-processor) 
``SDK MUST allow users to implement and configure custom processors and decorate built-in processors for advanced scenarios such as tagging or filtering.``
So those have to be taken care off as well. (Not to mention, that I apprently cannot read and implemented an exporter decorator instead of a processor decorator -  but that's easy to fix and the exporter decorator can be handy as well)

Do I know all the answers to above questions? No, but you wanted  ~~cheesecake~~ feeback. I hope this counts, but feel free to ignore it. 

However I am still working on the exporter ceation/factory issues, which are kind of a blocker for a TraceProviderFactory. 
And there is also [this issue](https://github.com/open-telemetry/opentelemetry-php/issues/301), which you can take into account (or take over if you like).

**Comment by bobstrecansky** [comment]
I think this would be a worthwhile endeavor!

**Comment by brettmc** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-php/pull/469
