### ISSUE TITLE
Integrate PHP app with OTLP Exporter to send traces to aws-otel-collector

### ISSUE THREAD

**Issue by farooqte96** [open-telemetry/opentelemetry-php#534]
Hi

I have a PHP application for which i want to send traces to aws-xray. It looks like we need to manually instrument the PHP application so it sends first all traces to [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md) using OTLP Exporter. I checked the example implementation provided here: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/AlwaysOnOTLPGrpcExample1.php  but i am unsure if i need to add include the code mentioned from line 29 onwards. As i am not much aware of PHP stack, can someone assist or give me some pointers how can i integrate an existing PHP application to forward the traces to 'aws-otel-collector'.
Thanks

**Comment by brettmc** [comment]
Hi @farooqte96
AlwaysOnOTLPGrpcExample[1+2].php look like they have not been updated since we made some changes, they definitely will not work. I haven't personally used it, but there is an example for aws-xray over in https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/examples/aws - scanning over them, they also need updating (contributions welcome!!) - but I think if you use one of those examples in conjunction with `AlwaysOnOTLPGrpcExample.php`, you might have more luck.

**Comment by tidal** [comment]
Yes, the AWS examples need an update -> https://github.com/open-telemetry/opentelemetry-php-contrib/issues/35

I did not include these changes, when updating the AWS components' code to work with the latest SDK changes.

@farooqte96 These changes are not releaes yet, but in the main branch, and we are working on publishing the AWS components (and other components) as a separate package.
