### ISSUE TITLE
Stackdriver Exporter

### ISSUE THREAD

**Issue by enumag** [open-telemetry/opentelemetry-php#577]
I'd like to use OpenTelemetry PHP and connect it to https://cloud.google.com/trace.

It seems that an exporter for Stackdriver doesn't exist yet and couldn't find an issue for it either.

How difficult do you think it would be?

**Comment by tidal** [comment]
> It seems that an exporter for Stackdriver doesn't exist yet and couldn't find an issue for it either.

No there is neither an exporter for Stackdriver nor an issue yet. We are still in the process of getting the library stable, so that's where our main focus is at the moment. However feel free to create a feature request for whatever you think would be a worthwhile addition. There is a lot of stuff missing at the moment.

> How difficult do you think it would be?

I am not familiar with the specifics of Stackdriver/Google Cloud Trace, but from takinga brief look at the documentation, it doesn't look too complicated.
The main part would be to create a SpanConverter which translates Otel Span into the Google format.
From what I have seen there is a [Stackdriver Client library](https://github.com/googleapis/google-cloud-php-trace), which could be leveraged. The downside is, that it uses `google/cloud-core` which has a hard dependency on `Guzzle` for HTTP requests, which we try to avoid, but I guess that would be ok for a contrib exporter.

Anyway in general such an eporter would go into the [opentelemetry-php-contrib
](https://github.com/open-telemetry/opentelemetry-php-contrib) repository.

**Comment by bobstrecansky** [comment]
You can also perform this action with our current state by posting to the OpenTelemetry collector and having the collector communicate with Google Cloud Trace.  I'm very familiar with this setup and have used something similar in a production environment.  Happy to answer other questions.

**Comment by enumag** [comment]
@bobstrecansky Can you share some details how to make the collector communicate with cloud trace? I couldn't find any mention of Stackdriver or GCP or anything related in the [docs](https://opentelemetry.io/docs/collector/).

**Comment by enumag** [comment]
@bobstrecansky What I'm confused about is how does the collector authenticate to Google Cloud to be able to send data there? Your example doesn't have any place where some authentication token would go...

**Comment by bobstrecansky** [comment]
Oh!  You must create a service account in GCP with the proper permissions.  You can generate credentials in JSON format, and use the `GOOGLE_APPLICATION_CREDENTIALS` environment variable for authentication.

**Comment by bobstrecansky** [comment]
Documentation for this can be found here:
https://cloud.google.com/docs/authentication/getting-started

**Comment by enumag** [comment]
Ah so basically the collector just requires the `GOOGLE_APPLICATION_CREDENTIALS` env var and it will work. Alright, that sounds cool!

**Comment by bobstrecansky** [comment]
@enumag - I'm going to close this because I think we've resolved all your issues.  Feel free to reopen if needed.
