### ISSUE TITLE
Jaeger thrift exporter exports spanIds as "7fffffff" for some IDs

### ISSUE THREAD

**Issue by DrLuke** [open-telemetry/opentelemetry-php#631]
The Jaeger `SpanConverter` converts the hexadecimal `spanId` to an integer [here](https://github.com/open-telemetry/opentelemetry-php/blob/2b72c92fcb30ed241c64c2bea613e7d3bb6ac7cb/src/Contrib/Jaeger/SpanConverter.php#L103), which is then, according to the [thrift span specification](https://github.com/open-telemetry/opentelemetry-php/blob/2b72c92fcb30ed241c64c2bea613e7d3bb6ac7cb/thrift/jaeger/SpanRef.php#L42), converted to a 64-bit **signed** integer.

The problem is that intval will interpret the hexadecimal `spanId` as an **unsigned** integer. Thus any ID that starts with `8` or greater will get capped at the maximum 64-bit signed integer value of `7FFFFFFF`.

I guess this also affects `traceId`s.

**Comment by tidal** [comment]
@DrLuke 
Thank you for the bug report.

**Comment by tidal** [comment]
@Grunet 
Could you take a look at this?

**Comment by DrLuke** [comment]
```php
$spanId = intval($span->getContext()->getSpanID(), 16) - 0x100000000;
$parentSpanId = intval($span->getParentSpanId(), 16) - 0x100000000;
```

Should do the trick to shift the value into the correct range

**Comment by Grunet** [comment]
Yeah that looks accurate to me from what I can tell. The other languages I double checked all seem to have built-in ways of converting from 64-bit byte strings to uint64 to int64 seamlessly, but I haven't been able to find an equivalent in PHP so far (since uint64 doesn't exist?).

I think @DrLuke 's shifting solution will probably work, maybe with some extra handling for when the uint64 should be above 2^63 - 1, since I'm not sure what intval will do to those just yet.

I'll write some more tests to get a better sense of these cases and then see if I can find an implementation for them in a PR

**Comment by tidal** [comment]
@Grunet 
Ok, thank you.
I suggest you can just write an integration test as a regression test, because there are a lot of parts/classes involved.

**Comment by Grunet** [comment]
FYI I've been running into precision issues with subtracting large integers. Like if I try to do (2^63 - 1) - (2^63) I end up with 0 instead of -1

```
print 9223372036854775807-9223372036854775808;
//Outputs 0 
```

But if I instead try using the[ bcmath](https://www.php.net/manual/en/book.bc.php) extension's functions (in an online repl, the dev image doesn't seem to have it) I can get the correct answer
```
print bcsub('9223372036854775807', '9223372036854775808');
//Outputs -1
```

I haven't been able to find a package version of this functionality yet (the [gmp extension](https://www.php.net/manual/en/book.gmp.php) has also come up as a way to tackle this, but I'm assuming otel-php can't require consumers to have extensions installed?)

**Comment by Grunet** [comment]
Ah I did just find [brick\math](https://github.com/brick/math) that seems like it provides "BigInteger" style arbitrary precision arithmetic capabilities.

I'll give it a go to see if it works here without the bcmath or gmp extensions (though I think the READme says it will use those if installed) but does this feel like the right option if so? It seems [pretty popular on Packagist](https://packagist.org/packages/brick/math) at least

**Comment by Grunet** [comment]
Yeah that seemed to knockout all my test cases in one fell swoop using @DrLuke 's strategy.

I'll go ahead and plan to get a clean PR with that in place later today.
