### ISSUE TITLE
Create OpenTracing Shim

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#747]
Specification Reference:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md
OpenTracing PHP repository:
https://github.com/opentracing/opentracing-php

**Comment by Grunet** [comment]
I'm guessing this one doesn't need to be thought out from scratch too much, and just following along with another language's implementation (or 2) with the spec at hand will get 90% of the way there.

Like for JS it looks like they managed this in roughly 400 lines of TS code - https://github.com/open-telemetry/opentelemetry-js/tree/f59c5b268bd60778d7a0d185a6044688f9e3dd51/packages/opentelemetry-shim-opentracing

If no one's able to pick this up after the next week or so, I might be able to and take a crack at it

**Comment by bobstrecansky** [comment]
@Grunet - are you still planning on working on this?

**Comment by Grunet** [comment]
Looking at it more closely now, I have 2 other observations

1) [JS](https://github.com/open-telemetry/opentelemetry-js/blob/f59c5b268bd60778d7a0d185a6044688f9e3dd51/packages/opentelemetry-shim-opentracing/src/shim.ts) and [Python](https://github.com/open-telemetry/opentelemetry-python/blob/71e3a7a192c0fc8a7503fac967ada36a74b79e58/shim/opentelemetry-opentracing-shim/src/opentelemetry/shim/opentracing_shim/__init__.py) keep all of the Shim classes in a single file, but [Java](https://github.com/open-telemetry/opentelemetry-java/tree/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/opentracing-shim/src/main/java/io/opentelemetry/opentracingshim) separates them out into their own files with the usual 1 per class deal. Since PHP/this repo has the same style, Java is probably the example to follow most closely.
2. The other repos all seem to publish a separate package for this shim, which the spec itself seems to kinda mandate when it says "This functionality MUST be defined in its own OpenTracing Shim Layer, not in the OpenTracing nor the OpenTelemetry API or SDK". So presumably the same needs to be done here, meaning the "gitsplit" setup needs to be extended I believe (initially added [in this PR](https://github.com/open-telemetry/opentelemetry-php/pull/682)).

I'm starting at a new gig next week so won't have much time right after that probably, but I do have a day off before then, so I will see how far I can get with 1) and then drop any notes on partial/progress here

**Comment by Grunet** [comment]
So there are a total of 27 methods across 5 interfaces that you need to fill out to make any OpenTracing-PHP implementation (including an OTEL-backed one as is needed here)

Scaffolding the initial files and taking a stab at the first 7 methods for OpenTracing's "Tracer" interface ended up taking me roughly around 7 hours (a large chunk of which was trying to understand-then-translate Java and JS's behaviors for the methods I didn't conceptually understand as well up front. I'm looking at you propagation lol). I also totally skipped some things for that interface implementation (like translating span creation options between OpenTracing and OTEL) just to try to get something in place for all of the methods.

You can see where I got to here - https://github.com/Grunet/opentelemetry-php/pull/6/files

I sadly most likely won't have mind energy in the next few weeks to carry this to completion, so anyone feel free to pick up from there as needed (but I will also aim to loop back if/when I do to see how I can help!)

**Comment by brettmc** [comment]
It looks like no other SIG has implemented this yet: https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#opentracing-compatibility so, my vote is to drop this as a requirement for a GA release.
