### ISSUE TITLE
Symfony Instrumentation

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#914]
@cedricziel was working on this PR for Symfony instrumentation: https://github.com/open-telemetry/opentelemetry-php-contrib/pull/58

He had to close it due to a lack of time.  Anthony Tetlow may be working on something similar.  Following up with him.

**Comment by codedge** [comment]
Just to get an idea: Is there someone, Anthony Teltow(?), actively working on? I saw the PR started by @cedricziel, which looked quite good, but I understand this has been stopped due to time constraints.

The question is: Is there another WIP version (PR), where support is needed?

**Comment by piotrantosik** [comment]
@codedge look here: https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/Symfony
I use this with custom logic (i mean instancing sdk in `index.php`), this week I deployed it into production app, works perfectly.
Also, I have internal instrumentation with Symfony Http Client - need to fix some bugs and next week I will try to prepare PR.

**Comment by sebb-m0** [comment]
Hey @piotrantosik. Any updates from your side with the PR? Can we support you in any way?

**Comment by piotrantosik** [comment]
Hi all, PR with Symfony HTTP Client -> https://github.com/open-telemetry/opentelemetry-php-contrib/pull/130
Please look on it and test if you have a possibility.

**Comment by codedge** [comment]
@piotrantosik
I think we misunderstood here. What I would expect is an integration into the Symfony framework, so that you can install a bundle, that

- hooks into every request and collect information
- gives you a `config/packages/opentelemetry.yaml` to configure option to your needs, f. ex. where do you want to collect data: Elasticsearch, Prometheus, .. 
- adds a `JAEGER_URL` env var in your `.env` file
- adds a `PROMETHEUS_URL` env var in your `.env` file .. so the data is automatically exported to the configured backend...

When looking at the [closed PR](https://github.com/open-telemetry/opentelemetry-php-contrib/pull/58) this was exactly what @cedricziel would have done.

Is that what you, @piotrantosik, are implementing now or did I understand something wrong?

**Comment by piotrantosik** [comment]
No, I don't create any bundle - I'm focused right now on auto instrumentation.
In my SF project, I enable collector via configuring SDK, I want to update readme with similar code to this example: https://gist.github.com/piotrantosik/56d7ab585fe1c5c96e028cd6c08f7de5

I don't think a bundle will be needed, everything can be set up via ENV variables and SDK.

**Comment by brettmc** [comment]
I think we can close this, since https://github.com/open-telemetry/opentelemetry-php-contrib/pull/169 has gotten Symfony instrumentation back in working order.
