### ISSUE TITLE
Missing google/protobuf implementation is failing when trying to use application/json as transport

### ISSUE THREAD

**Issue by MetalArend** [open-telemetry/opentelemetry-php#957]
> Unhandled export error {"exception":"[object] (Error(code: 0): Class \"Google\\Protobuf\\Internal\\Message\" not found at /var/vhost/vendor/open-telemetry/gen-otlp-protobuf/Opentelemetry/Proto/Collector/Trace/V1/ExportTraceServiceRequest.php:14)","source":"OpenTelemetry\\SDK\\Trace\\SpanProcessor\\BatchSpanProcessor"}

Once I added `LoggerHolder::set($logger);`, my logs showed me this error. Took me a bit to figure out why the class was missing. But it didn't make sense why it would be needed.

I would expect the open-telemetry library to error out hard (throw an Exception even) at something like this line `(new OtlpHttpTransportFactory())->create($url, 'application/x-protobuf')`, if no protobuf implementation could be found. But it is also used when I use `application/json`, because somehow that's also needing the `Google\Protobuf\Internal\Message` class.

I understand that not having the native library as a default dependency is a recent change. It's also a shame that the native library implementation is not checking if an extension already has provided the class. So it certainly makes sense to have to manually install the package `google/protobuf` if you try to use protobuf. But why is it needed when I'm trying to use json?

**Comment by brettmc** [comment]
Internally, all OTLP-based encodings (grpc, http/protobuf, http/json) are converted via protobuf, because although in this case the output is JSON, it still needs to conform to the otel spec (which we get for free by using common otel proto files).
The spec does allow some room to fail hard at constructor/setup time, so I've added a PR for a runtime check/exception if no implementation is found.
