### ISSUE TITLE
Removal of 0.0.16 from Packagist - intentional?

### ISSUE THREAD

**Issue by c-zoa** [open-telemetry/opentelemetry-php#980]
It appears open-telemetry/opentelemetry 0.0.16 has been removed from [Packagist](https://packagist.org/packages/open-telemetry/opentelemetry).

Is this intentional?

If this is intentional other packages will have to update their dependencies but just asking the question as it seems odd it'd be removed entirely.

**Steps to reproduce**

For example, following composer init:

```
composer req uptrace/uptrace:0.1.2
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update uptrace/uptrace
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires uptrace/uptrace 0.1.2 -> satisfiable by uptrace/uptrace[v0.1.2].
    - uptrace/uptrace v0.1.2 requires open-telemetry/opentelemetry 0.0.16 -> found open-telemetry/opentelemetry[dev-main, 1.0.0beta, 1.0.0beta1] but it does not match the constraint.


Installation failed, reverting ./composer.json to its original content.
```

**What is the expected behavior?**

Version 0.0.16 to be there.

**What is the actual behavior?**

Version 0.0.16 is not there.

**Comment by brettmc** [comment]
Hi @c-zoa 
Yes, it was intentionally removed (actually, the old deprecated package was replaced with a meta-package, since we changed how we version everything to align better with the OpenTelemetry spec).
I'd recommend that you update your dependencies to require the package(s) you need, such as `open-telemetry/sdk 0.0.16` (or better yet, try out our betas). Taking a quick scan of your code, it looks like you want `sdk`, `exporter-otlp`, `semconv`.

**Comment by c-zoa** [comment]
Hi Brett. Okay, thank you for your reply and having a look.
