### ISSUE TITLE
Avoid blocking on sending traces upstream at the end of each request?

### ISSUE THREAD

**Issue by lf-** [open-telemetry/opentelemetry-php#993]
**Is your feature request related to a problem?**

When I implemented OpenTelemetry tracing in the application I'm working on, it seems to be blocking on sending requests to the OTLP service before sending the response to the web client. I am not sure if it is something I screwed up or a fundamental consequence of PHP's execution model (since the script is run start to end on every request; there is not really persistent state? Or at least that's my understanding?). Please feel free to close this if it is just how it has to work; I am very new to PHP.

I've worked with the OpenTelemetry systems for Rust and Haskell and they do not do this (because they both spawn a background thread that survives multiple requests to send the data out; which I am unsure if PHP allows for?).

**Describe the solution you'd like**

Ideally I would like for traces to be sent in a non-blocking fashion without affecting the response time of the request.

**Describe alternatives you've considered**

Possibly set up Honeycomb Refinery or similar proxy so that even though it is blocking, it's not going to get rate limited/etc and will batch multiple requests worth of traces at a time to Honeycomb.

**Additional context**

Versions, if it is something that would be fixed by upgrading to newer versions of things (we're working on it)

```
php -v
PHP 7.4.33 (cli) (built: Oct 31 2022 10:36:16) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```

```
    "open-telemetry/api": "^0.0.17",
    "open-telemetry/sdk": "^0.0.17",
    "symfony/http-client": "^5.4",
    "nyholm/psr7": "^1.8",
    "guzzlehttp/promises": "^1.5",
    "php-http/message-factory": "^1.1",
    "open-telemetry/exporter-otlp": "^0.0.17",
    "psr/http-client": "^1.0"
```

**Comment by lf-** [comment]
Hmm. Our HTTP server ends response processing with `exit()` but this seems to not immediately finish the request. I wonder if this could be resolved by `session_write_close(); fastcgi_finish_request()`.

To some extent, yes, this is our fault, but I also think that otel-php having to submit all the traces for a request at the end of the request needs to be documented if it's not already.

**Comment by brettmc** [comment]
Hello. Yes, you are correct that the sending of telemetry is blocking. Whether that blocks the sending of responses to the client or not depends on the PHP runtime you use. If you're using fastcgi then you can use `fastcgi_finish_request` so that the client does not wait on sending telemetry.

Depending on the processor you use (simple, batch) and the processing time of the request, some telemetry may be sent _during_ the processing as well; a longer-running request is more likely to exceed the export delay.

We have plans for async sending in a future release, but in a shared-nothing webserver (eg nginx+fcgi, apache+mod_php), I think it will always be true that the process must remain active until telemetry is sent (there is no fire-and-forget method of sending telemetry, eg via UDP).

If you are using a newer runtime such as roadrunner, react, amp then you have more options for non-blocking/async sending.

We're always happy to accept doc patches (preferably over in opentelemetry.io, which is our official documentation source)

**Comment by brettmc** [comment]
Added some documentation around blocking: https://github.com/open-telemetry/opentelemetry.io/pull/2727
